sign-commit = true
sign-tag = true
pre-release-commit-message = "Release {{crate_name}} {{version}} 🎉🎉"
tag-message = "Release {{crate_name}} {{prefix}}{{version}}"
tag-prefix = ""
tag-name = "{{prefix}}{{version}}"

pre-release-replacements = [
    { file = "README.md", search = "actix-web-validator = \"[a-z0-9\\.-]+\"", replace = "actix-web-validator = \"{{version}}\"" },
    { file = "CHANGELOG.md", search = "\\[Unreleased\\]", replace = "[{{version}}] {{date}}" },
    { file = "CHANGELOG.md", search = "\\(https://semver.org/spec/v2.0.0.html\\).", replace = "(https://semver.org/spec/v2.0.0.html).\n\n## [Unreleased]" },
]
